{{- range $moduleName, $value := .Values.module }}
{{- $kebabedModuleName := $moduleName | kebabcase }}
{{- if and $value.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "container-image-sync.fullname" $ }}-{{ $kebabedModuleName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "container-image-sync.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
spec:
  template:
    metadata:
      annotations:
        checksum/configMap: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
      {{- with $.Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "container-image-sync.labels" $ | nindent 8 }}
        {{- with $.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: OnFailure
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "container-image-sync.serviceAccountName" $ }}
      serviceAccount: {{ include "container-image-sync.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: fetch-images
          {{- include "container-image-sync.skopeo" $ | nindent 10 }}
          {{- with $value.image }}
          image: {{ .registry }}{{ .repository }}:{{ .tag }}
          {{- end }}
          command: [ "/bin/sh", "-c" ]
          args: 
            - |
              /opt/audax/module/common-config/entrypoint.sh version {{ .imageSyncDomain }} > /opt/audax/container-image-sync/services-definition.yaml
        - name: process-service-images
          args: ["--process-service-images"]
          {{- include "container-image-sync.skopeo" $ | nindent 10 }}
        - name: create-image-repos
          args: ["--create-image-repos"]
          {{- include "container-image-sync.awscli" $ | nindent 10 }}
      containers:
        - name: sync-images
          args: ["--sync-images"]
          {{- include "container-image-sync.skopeo" $ | nindent 10 }}
      {{- with $.Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}