{{- if .Values.target.auth.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.target.auth.serviceAccount.role }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
  name: {{ default .Release.Name .Values.target.auth.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{- end }}