{{- if eq .Values.authType "kubeConfig" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeconfig
  {{- if not $.Values.argocdDeployer }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
  {{- end }}
data:
  kubeconfig.yaml: |-
{{ .Files.Get "kubeconfig.yaml" | indent 4}}

{{- end }}