environment: ""
action: apply
env: ""
shortEnv:  ""
cassandraKeyspace: ""

module: {}
deployer:
  image:
    registry: ""
    repository: "audax-io/deployer"
    tag: "v6.1.7.1"
    args:
  httpServer:
    port: 8080 

securityContext:
  supplementalGroups:
  - 10000
podSecurityContext:
  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsGroup: 10000
    runAsUser: 10000


enableSupplementalGroups: true

moduleConfig: {}

scheduling: {}

serviceAccount:
  create: false
  name: ax-dev-sg-wid-jenkins-agent
  role: ''

nodeAffinity:
  key: audax.io/nodegroup
  value: ax-dev-sg-cpl-infra-ng
##auth type:
## IRSA - use IRSA role and service account
## kubeConfig - provide kubeconfig.yaml in pipeline as configmap
authType: kubeConfig

proxy:
  enabled: false
  http_proxy: ""
  https_proxy: ""
  no_proxy: ""

argocdDeployer: false
