{{- if .Values.source.auth.secretRef.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "container-image-sync.fullname" . }}-secret
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
type: Opaque
data:
  ghcr-token: {{ .Values.source.auth.token | b64enc | quote }}
  ghcr-user: {{ .Values.source.auth.username | b64enc | quote }}
  ecr-user: {{ "AWS" | b64enc | quote }}
{{- end }}